server:
  port: 80
erpDatasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://139.129.203.216:3306/erp?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
  username: root
  password: root
web:
  front:
    base-dir: erp_web
mybatis:
  mapperLocations: classpath:mapper_xml/*.xml  #一定要对应mapper映射xml文件的所在路径
  executorType: SIMPLE